# Generated by Django 5.2.7 on 2026-02-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
