# Generated by Django 5.2.7 on 2026-02-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
