# Generated by Django 5.2.7 on 2026-03-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
